### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by WeltonLSantos** [Webschool-io/Curso-PHP-Laravel-Completo-E-Total#3]
> Não vai dar continuidade?

**Comment by michaeldouglas** [comment]
Opa, a partir de amanhã já terá mais coisas (rs)

**Comment by hc3** [comment]
tem algum livro para indicar?

**Comment by spaceonline** [comment]
como será a aplicação da ementa? Iremos produzir juntos um projeto? Tenho um projeto já iniciado em laravel5.2 muito show, saas com cobranças e módulos, caso tenha interesse podemos trabalhar algo dentro dele no curso, o projeto final pode facilitar para todos os alunos um esquema pronto para escalar em módulos.

**Comment by marabesi** [comment]
Como não houve nenhuma resposta vou fechar essa issue, pois creio que a mesma já foi resolvida de uma outra forma.
